apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend-dep
    tier: web-dep
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodeport }}